import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { cookies } from "next/headers"
import { AnimatedThemeToggler } from "@/components/ui/animated-theme-toggler"

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by Jose Otero",
};

export default async function Layout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <html lang="en">
      <body className="h-full overflow-hidden">
        <AnimatedThemeToggler className="fixed top-4 right-4 z-50" duration={1000}/>
        <SidebarProvider defaultOpen={defaultOpen} className="h-full">
          <AppSidebar />
          <main className="flex flex-col h-full w-full overflow-hidden">
            <div className="flex-shrink-0 p-2">
              <SidebarTrigger />
            </div>
            <div className="flex-1 overflow-auto">
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>

  )
}



